---

parser: "@typescript-eslint/parser"

parserOptions:
  requireConfigFile: false
  babelOptions:
    root: /usr/src/linter
  project:
    - "./tsconfig.json"

extends:
  - airbnb
  - "airbnb-typescript"
  - "plugin:jest/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:@typescript-eslint/recommended"

plugins:
  - jest
  - "@babel"
  - "@typescript-eslint"

env:
  node: true
  jest: true
  browser: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  no-underscore-dangle:
    - error
    - allow:
      - __dirname
      - __filename
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
