---

parser: babel-eslint
extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

plugins:
  - babel
  - jest

env:
  node: true
  jest/globals: true
  browser: true

rules:
  import/no-unresolved: "off"
  import/extensions: "off"
