---

parser: "@babel/eslint-parser"

parserOptions:
  requireConfigFile: false
  babelOptions:
    root: /usr/src/app

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

plugins:
  - jest
  - "@babel"

env:
  node: true
  jest: true
  browser: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
  no-underscore-dangle:
    - error
    - allow:
      - __dirname
      - __filename
